/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutAs: typeof import('./src/components/AboutAs.vue')['default']
    AboutUs: typeof import('./src/components/AboutUs.vue')['default']
    AwardModal: typeof import('./src/components/AwardModal.vue')['default']
    AwardsShowcase: typeof import('./src/components/AwardsShowcase.vue')['default']
    BaseFormGroup: typeof import('./src/components/Base/BaseFormGroup.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LibraryGallery: typeof import('./src/components/LibraryGallery.vue')['default']
    RouteOfTheMonth: typeof import('./src/components/RouteOfTheMonth.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RouteVoting: typeof import('./src/components/RouteVoting.vue')['default']
  }
}
