/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutAs: typeof import('./src/components/AboutAs.vue')['default']
    AboutUs: typeof import('./src/components/AboutUs.vue')['default']
    AppModal: typeof import('./src/components/AppModal.vue')['default']
    AwardModal: typeof import('./src/components/AwardModal.vue')['default']
    AwardsShowcase: typeof import('./src/components/AwardsShowcase.vue')['default']
    BaseFormGroup: typeof import('./src/components/Base/BaseFormGroup.vue')['default']
    BookHeader: typeof import('./src/components/Book/BookHeader.vue')['default']
    BookReviewForm: typeof import('./src/components/Book/BookReviewForm.vue')['default']
    BookReviewList: typeof import('./src/components/Book/BookReviewList.vue')['default']
    ClubBookOfMonth: typeof import('./src/components/Club/ClubBookOfMonth.vue')['default']
    ClubBookPickerDialog: typeof import('./src/components/Club/ClubBookPickerDialog.vue')['default']
    ClubDiscussion: typeof import('./src/components/Club/ClubDiscussion.vue')['default']
    ClubFormPage: typeof import('./src/components/ClubFormPage.vue')['default']
    ClubHeader: typeof import('./src/components/Club/ClubHeader.vue')['default']
    ClubRecommendations: typeof import('./src/components/Club/ClubRecommendations.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LibraryGallery: typeof import('./src/components/LibraryGallery.vue')['default']
    NotificationBell: typeof import('./src/components/NotificationBell.vue')['default']
    ProfileAwards: typeof import('./src/components/Profile/ProfileAwards.vue')['default']
    ProfileFriends: typeof import('./src/components/Profile/ProfileFriends.vue')['default']
    ProfileInterests: typeof import('./src/components/Profile/ProfileInterests.vue')['default']
    RouteOfTheMonth: typeof import('./src/components/RouteOfTheMonth.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RouteVoting: typeof import('./src/components/RouteVoting.vue')['default']
    UserAvatarMenu: typeof import('./src/components/UserAvatarMenu.vue')['default']
  }
}
