/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/auth/Login': RouteRecordInfo<'/auth/Login', '/auth/Login', Record<never, never>, Record<never, never>>,
    '/auth/SignUp': RouteRecordInfo<'/auth/SignUp', '/auth/SignUp', Record<never, never>, Record<never, never>>,
    '/awards': RouteRecordInfo<'/awards', '/awards', Record<never, never>, Record<never, never>>,
    '/books/[routeId]/[id]': RouteRecordInfo<'/books/[routeId]/[id]', '/books/:routeId/:id', { routeId: ParamValue<true>, id: ParamValue<true> }, { routeId: ParamValue<false>, id: ParamValue<false> }>,
    '/routes': RouteRecordInfo<'/routes', '/routes', Record<never, never>, Record<never, never>>,
    '/user': RouteRecordInfo<'/user', '/user', Record<never, never>, Record<never, never>>,
  }
}
